### ISSUE TITLE
Failing tests

### ISSUE THREAD

**Issue by jacek99** [couchbaselabs/java-dcp-client#1]
Just cloned the repo on Fedora 24 (with Maven 3.3.9) and I got JUnit test failures when running

```
mvn install
```

Details:

```
Downloaded: https://repo.maven.apache.org/maven2/org/apache/maven/surefire/surefire-junit4/2.12.4/surefire-junit4-2.12.4.jar (37 KB at 1092.6 KB/sec)

-------------------------------------------------------
 T E S T S
-------------------------------------------------------
Running com.couchbase.client.dcp.message.control.OpenConnectionRequestTest
15:48:30.125 [main] DEBUG c.c.c.d.i.n.u.i.l.InternalLoggerFactory - Using SLF4J as the default logging framework
15:48:30.129 [main] DEBUG c.c.c.d.i.n.u.i.PlatformDependent0 - java.nio.Buffer.address: available
15:48:30.130 [main] DEBUG c.c.c.d.i.n.u.i.PlatformDependent0 - sun.misc.Unsafe.theUnsafe: available
15:48:30.130 [main] DEBUG c.c.c.d.i.n.u.i.PlatformDependent0 - sun.misc.Unsafe.copyMemory: available
15:48:30.130 [main] DEBUG c.c.c.d.i.n.u.i.PlatformDependent0 - java.nio.Bits.unaligned: true
15:48:30.131 [main] DEBUG c.c.c.d.i.n.u.i.PlatformDependent - Java version: 8
15:48:30.131 [main] DEBUG c.c.c.d.i.n.u.i.PlatformDependent - -Dio.netty.noUnsafe: false
15:48:30.131 [main] DEBUG c.c.c.d.i.n.u.i.PlatformDependent - sun.misc.Unsafe: available
15:48:30.132 [main] DEBUG c.c.c.d.i.n.u.i.PlatformDependent - -Dio.netty.noJavassist: false
15:48:30.132 [main] DEBUG c.c.c.d.i.n.u.i.PlatformDependent - Javassist: unavailable
15:48:30.133 [main] DEBUG c.c.c.d.i.n.u.i.PlatformDependent - You don't have Javassist in your class path or you don't have enough permission to load dynamically generated classes.  Please check the configuration for better performance.
15:48:30.133 [main] DEBUG c.c.c.d.i.n.u.i.PlatformDependent - -Dio.netty.tmpdir: /tmp (java.io.tmpdir)
15:48:30.133 [main] DEBUG c.c.c.d.i.n.u.i.PlatformDependent - -Dio.netty.bitMode: 64 (sun.arch.data.model)
15:48:30.133 [main] DEBUG c.c.c.d.i.n.u.i.PlatformDependent - -Dio.netty.noPreferDirect: false
15:48:30.139 [main] DEBUG c.c.c.d.i.n.buffer.AbstractByteBuf - -Dcom.couchbase.client.deps.io.netty.buffer.bytebuf.checkAccessible: true
15:48:30.140 [main] DEBUG c.c.c.d.i.n.u.ResourceLeakDetector - -Dcom.couchbase.client.deps.io.netty.leakDetection.level: simple
15:48:30.141 [main] DEBUG c.c.c.d.i.n.u.ResourceLeakDetector - -Dcom.couchbase.client.deps.io.netty.leakDetection.maxRecords: 4
15:48:30.152 [main] DEBUG c.c.c.d.io.netty.buffer.ByteBufUtil - -Dio.netty.allocator.type: unpooled
15:48:30.152 [main] DEBUG c.c.c.d.io.netty.buffer.ByteBufUtil - -Dio.netty.threadLocalDirectBufferSize: 65536
15:48:30.152 [main] DEBUG c.c.c.d.io.netty.buffer.ByteBufUtil - -Dio.netty.maxThreadLocalCharBufferSize: 16384
Tests run: 2, Failures: 2, Errors: 0, Skipped: 0, Time elapsed: 0.415 sec <<< FAILURE!
testInit(com.couchbase.client.dcp.message.control.OpenConnectionRequestTest)  Time elapsed: 0.369 sec  <<< FAILURE!
java.lang.AssertionError: expected:<24> but was:<32>
    at org.junit.Assert.fail(Assert.java:88)
    at org.junit.Assert.failNotEquals(Assert.java:834)
    at org.junit.Assert.assertEquals(Assert.java:645)
    at org.junit.Assert.assertEquals(Assert.java:631)
    at com.couchbase.client.dcp.message.control.OpenConnectionRequestTest.testInit(OpenConnectionRequestTest.java:37)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke(Method.java:498)
    at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)
    at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
    at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)
    at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
    at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:325)
    at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:78)
    at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:57)
    at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
    at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)
    at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
    at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)
    at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)
    at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
    at org.apache.maven.surefire.junit4.JUnit4Provider.execute(JUnit4Provider.java:252)
    at org.apache.maven.surefire.junit4.JUnit4Provider.executeTestSet(JUnit4Provider.java:141)
    at org.apache.maven.surefire.junit4.JUnit4Provider.invoke(JUnit4Provider.java:112)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke(Method.java:498)
    at org.apache.maven.surefire.util.ReflectionUtils.invokeMethodWithArray(ReflectionUtils.java:189)
    at org.apache.maven.surefire.booter.ProviderFactory$ProviderProxy.invoke(ProviderFactory.java:165)
    at org.apache.maven.surefire.booter.ProviderFactory.invokeProvider(ProviderFactory.java:85)
    at org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:115)
    at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:75)

testSetConnectionName(com.couchbase.client.dcp.message.control.OpenConnectionRequestTest)  Time elapsed: 0.007 sec  <<< FAILURE!
org.junit.ComparisonFailure: expected:<[name]> but was:<[]>
    at org.junit.Assert.assertEquals(Assert.java:115)
    at org.junit.Assert.assertEquals(Assert.java:144)
    at com.couchbase.client.dcp.message.control.OpenConnectionRequestTest.testSetConnectionName(OpenConnectionRequestTest.java:49)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke(Method.java:498)
    at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)
    at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
    at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)
    at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
    at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:325)
    at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:78)
    at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:57)
    at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
    at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)
    at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
    at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)
    at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)
    at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
    at org.apache.maven.surefire.junit4.JUnit4Provider.execute(JUnit4Provider.java:252)
    at org.apache.maven.surefire.junit4.JUnit4Provider.executeTestSet(JUnit4Provider.java:141)
    at org.apache.maven.surefire.junit4.JUnit4Provider.invoke(JUnit4Provider.java:112)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke(Method.java:498)
    at org.apache.maven.surefire.util.ReflectionUtils.invokeMethodWithArray(ReflectionUtils.java:189)
    at org.apache.maven.surefire.booter.ProviderFactory$ProviderProxy.invoke(ProviderFactory.java:165)
    at org.apache.maven.surefire.booter.ProviderFactory.invokeProvider(ProviderFactory.java:85)
    at org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:115)
    at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:75)


Results :

Failed tests:   testInit(com.couchbase.client.dcp.message.control.OpenConnectionRequestTest): expected:<24> but was:<32>
  testSetConnectionName(com.couchbase.client.dcp.message.control.OpenConnectionRequestTest): expected:<[name]> but was:<[]>

Tests run: 2, Failures: 2, Errors: 0, Skipped: 0

[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 17.117 s
[INFO] Finished at: 2016-08-08T15:48:30-05:00
[INFO] Final Memory: 19M/223M
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-surefire-plugin:2.12.4:test (default-test) on project dcp-client: There are test failures.
[ERROR] 
[ERROR] Please refer to /home/jfurmank/tmp/java-dcp-client/target/surefire-reports for the individual test results.
[ERROR] -> [Help 1]
[ERROR] 
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR] 
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/MojoFailureException
[jfurmank@jf76 java-dcp-client] $ 
```

**Comment by avsej** [comment]
@jacek99 what is the version of the server you are using?

**Comment by jacek99** [comment]
I am on 4.5, the latest version from your site, installed it via RPM a week ago

**Comment by avsej** [comment]
turns out that it was outdated test, thank you for reporting

**Comment by jacek99** [comment]
Confirmed. Did a git pull, built fine.

Thank you for the quick fix, much appreciated.
