### ISSUE TITLE
start two dcp client at same time

### ISSUE THREAD

**Issue by belaazim** [couchbaselabs/java-dcp-client#13]
Hi,
My use case is about starting two dcp clients at the same time:
I'm getting this issue:
java.lang.IllegalStateException: Unhandled Status: 2
    at com.couchbase.client.dcp.conductor.DcpChannel.filterOpenStreamResponse(DcpChannel.java:164)
Any idea about this please ?

**Comment by belaazim** [comment]
@daschl @avsej : Did you reproduce this issue ?

**Comment by avsej** [comment]
Could you share the test code, how do you initialize and run those clients?

**Comment by belaazim** [comment]
launch in parallel 2 clietns.
1. the first client from begining to no end
2. the second client from now to no end
Random issue reported in my previous message

**Comment by belaazim** [comment]
This is more log:
2016-09-29 18:38:23,251 [WARN, Conductor 165] Error during Partition Move for partition 420
java.lang.IllegalStateException: Unhandled Status: 2
    at com.couchbase.client.dcp.conductor.DcpChannel.filterOpenStreamResponse(DcpChannel.java:164)
    at com.couchbase.client.dcp.conductor.DcpChannel.access$000(DcpChannel.java:61)
    at com.couchbase.client.dcp.conductor.DcpChannel$2.call(DcpChannel.java:109)
    at com.couchbase.client.dcp.conductor.DcpChannel$2.call(DcpChannel.java:105)
    at rx.internal.operators.OnSubscribeFilter$FilterSubscriber.onNext(OnSubscribeFilter.java:67)
    at rx.subjects.SubjectSubscriptionManager$SubjectObserver.onNext(SubjectSubscriptionManager.java:225)
    at rx.subjects.PublishSubject.onNext(PublishSubject.java:113)
    at rx.observers.SerializedObserver.onNext(SerializedObserver.java:92)
    at rx.subjects.SerializedSubject.onNext(SerializedSubject.java:67)
    at com.couchbase.client.dcp.transport.netty.DcpMessageHandler.channelRead(DcpMessageHandler.java:70)
    at com.couchbase.client.deps.io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:366)
    at com.couchbase.client.deps.io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:352)
    at com.couchbase.client.deps.io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:345)

**Comment by belaazim** [comment]
@daschl @avsej : did you succeed in producing this issue ?

**Comment by belaazim** [comment]
An other issue opened with the log of this random issue.
