### ISSUE TITLE
Error during partition move

### ISSUE THREAD

**Issue by belaazim** [couchbaselabs/java-dcp-client#18]
Hi,
An error occurs in random way.  Any idea please ?
This is the log : 
2016-10-11 10:48:57,610 [WARN, Conductor 165] Error during Partition Move for partition 341
java.lang.IllegalStateException: Unhandled Status: 34
    at com.couchbase.client.dcp.conductor.DcpChannel.filterOpenStreamResponse(DcpChannel.java:164)
    at com.couchbase.client.dcp.conductor.DcpChannel.access$000(DcpChannel.java:61)
    at com.couchbase.client.dcp.conductor.DcpChannel$2.call(DcpChannel.java:109)
    at com.couchbase.client.dcp.conductor.DcpChannel$2.call(DcpChannel.java:105)
    at rx.internal.operators.OnSubscribeFilter$FilterSubscriber.onNext(OnSubscribeFilter.java:67)
    at rx.subjects.SubjectSubscriptionManager$SubjectObserver.onNext(SubjectSubscriptionManager.java:225)
    at rx.subjects.PublishSubject.onNext(PublishSubject.java:113)
    at rx.observers.SerializedObserver.onNext(SerializedObserver.java:92)
    at rx.subjects.SerializedSubject.onNext(SerializedSubject.java:67)
    at com.couchbase.client.dcp.transport.netty.DcpMessageHandler.channelRead(DcpMessageHandler.java:70)
    at com.couchbase.client.deps.io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:366)
    at com.couchbase.client.deps.io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:352)
    at com.couchbase.client.deps.io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:345)
    at com.couchbase.client.deps.io.netty.handler.codec.ByteToMessageDecoder.fireChannelRead(ByteToMessageDecoder.java:293)
    at com.couchbase.client.deps.io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:267)
    at com.couchbase.client.deps.io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:366)
    at com.couchbase.client.deps.io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:352)
    at com.couchbase.client.deps.io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:345)
    at com.couchbase.client.deps.io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1294)
    at com.couchbase.client.deps.io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:366)
    at com.couchbase.client.deps.io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:352)
    at com.couchbase.client.deps.io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:911)
    at com.couchbase.client.deps.io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:131)
    at com.couchbase.client.deps.io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:572)
    at com.couchbase.client.deps.io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:513)
    at com.couchbase.client.deps.io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:427)
    at com.couchbase.client.deps.io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:399)
    at com.couchbase.client.deps.io.netty.util.concurrent.SingleThreadEventExecutor$2.run(SingleThreadEventExecutor.java:140)
    at com.couchbase.client.deps.io.netty.util.concurrent.DefaultThreadFactory$DefaultRunnableDecorator.run(DefaultThreadFactory.java:144)
    at java.lang.Thread.run(Thread.java:745)

**Comment by belaazim** [comment]
@daschl: any idea about this ?

**Comment by daschl** [comment]
@avsej maybe?

**Comment by belaazim** [comment]
at least how to manage this exception in case it occurs ?
Thanks in advance :)

**Comment by avsej** [comment]
This code is intended to be handled by the library, and it is definitely issue of the client. It requested the sequence numbers of vbucket, which haven't seen it yet. I've converted it to the ticket https://issues.couchbase.com/browse/JDCP-29 and we will fix it there.
