### ISSUE TITLE
IllegalStateException: Unhandled Status: 2

### ISSUE THREAD

**Issue by belaazim** [couchbaselabs/java-dcp-client#31]
Hi,

Have you please an idea about this exception : 

Caused by: java.lang.IllegalStateException: Unhandled Status: 2
	at com.couchbase.client.dcp.conductor.DcpChannel.filterOpenStreamResponse(DcpChannel.java:164)
	at com.couchbase.client.dcp.conductor.DcpChannel.access$000(DcpChannel.java:61)
	at com.couchbase.client.dcp.conductor.DcpChannel$2.call(DcpChannel.java:109)
	at com.couchbase.client.dcp.conductor.DcpChannel$2.call(DcpChannel.java:105)
	at rx.internal.operators.OnSubscribeFilter$FilterSubscriber.onNext(OnSubscribeFilter.java:67)
	at rx.subjects.SubjectSubscriptionManager$SubjectObserver.onNext(SubjectSubscriptionManager.java:225)

Thanks in advance,
Maherzia

**Comment by avsej** [comment]
Could you please open the ticket through Jira? https://issues.couchbase.com/projects/JDCP

Thank you

**Comment by belaazim** [comment]
I'm not a couchbase member. Could you please add it on the JIRA and share the jira link to follow the status of this issue ?
Thanks in advance

**Comment by belaazim** [comment]
Hi  
@avsej : Any news please about this bug ?
It is random and once it occurs it causes the skip of mutation messages.
Thanks in advance

**Comment by zzvara** [comment]
I've got the same problem here, while reading two couchbaseStreams in Spark.

**Comment by abrandwi** [comment]
I got this exception too:
```
2017-05-15 11:31:17.257  WARN --- [nioEventLoopGroup-5-1] c.c.c.d.c.Conductor warn: Error during Partition Move for partition 197
java.lang.IllegalStateException: Unhandled Status: 2
        at com.couchbase.client.dcp.conductor.DcpChannelControlHandler.filterOpenStreamResponse(DcpChannelControlHandler.java:95) [dcp-client-0.10.0.jar!/:?]
        at com.couchbase.client.dcp.conductor.DcpChannelControlHandler.onEvent(DcpChannelControlHandler.java:53) [dcp-client-0.10.0.jar!/:?]
        at com.couchbase.client.dcp.transport.netty.DcpMessageHandler.channelRead(DcpMessageHandler.java:89) [dcp-client-0.10.0.jar!/:?]
        at com.couchbase.client.deps.io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:356) [core-io-1.4.5.jar!/:?]
        at com.couchbase.client.deps.io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:342) [core-io-1.4.5.jar!/:?]
        at com.couchbase.client.deps.io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:335) [core-io-1.4.5.jar!/:?]
        at com.couchbase.client.deps.io.netty.handler.codec.ByteToMessageDecoder.fireChannelRead(ByteToMessageDecoder.java:293) [core-io-1.4.5.jar!/:?]
        at com.couchbase.client.deps.io.netty.handler.codec.ByteToMessageDecoder.fireChannelRead(ByteToMessageDecoder.java:280) [core-io-1.4.5.jar!/:?]
        at com.couchbase.client.deps.io.netty.handler.codec.ByteToMessageDecoder.callDecode(ByteToMessageDecoder.java:396) [core-io-1.4.5.jar!/:?]
        at com.couchbase.client.deps.io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:248) [core-io-1.4.5.jar!/:?]
        at com.couchbase.client.deps.io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:356) [core-io-1.4.5.jar!/:?]
        at com.couchbase.client.deps.io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:342) [core-io-1.4.5.jar!/:?]
        at com.couchbase.client.deps.io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:335) [core-io-1.4.5.jar!/:?]
        at com.couchbase.client.deps.io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1294) [core-io-1.4.5.jar!/:?]
        at com.couchbase.client.deps.io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:356) [core-io-1.4.5.jar!/:?]
        at com.couchbase.client.deps.io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:342) [core-io-1.4.5.jar!/:?]
        at com.couchbase.client.deps.io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:911) [core-io-1.4.5.jar!/:?]
        at com.couchbase.client.deps.io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:131) [core-io-1.4.5.jar!/:?]
        at com.couchbase.client.deps.io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:625) [core-io-1.4.5.jar!/:?]
        at com.couchbase.client.deps.io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:560) [core-io-1.4.5.jar!/:?]
        at com.couchbase.client.deps.io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:477) [core-io-1.4.5.jar!/:?]
        at com.couchbase.client.deps.io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:439) [core-io-1.4.5.jar!/:?]
        at com.couchbase.client.deps.io.netty.util.concurrent.SingleThreadEventExecutor$2.run(SingleThreadEventExecutor.java:131) [core-io-1.4.5.jar!/:?]
        at com.couchbase.client.deps.io.netty.util.concurrent.DefaultThreadFactory$DefaultRunnableDecorator.run(DefaultThreadFactory.java:144) [core-io-1.4.5.jar!/:?]
        at java.lang.Thread.run(Thread.java:745) [?:1.8.0_121]
```

And before that:
```
2017-05-15 11:31:16.664  WARN --- [RxComputationScheduler-1] c.c.c.d.c.Conductor warn: Error during Partition Move for partition 50
java.lang.NullPointerException
        at com.couchbase.client.dcp.conductor.DcpChannel$5.call(DcpChannel.java:300) ~[dcp-client-0.10.0.jar!/:?]
        at com.couchbase.client.dcp.conductor.DcpChannel$5.call(DcpChannel.java:274) ~[dcp-client-0.10.0.jar!/:?]
        at rx.Completable.unsafeSubscribe(Completable.java:2035) ~[rxjava-1.3.0.jar!/:1.3.0]
        at rx.Completable.unsafeSubscribe(Completable.java:2083) ~[rxjava-1.3.0.jar!/:1.3.0]
        at rx.Completable.unsafeSubscribe(Completable.java:2067) ~[rxjava-1.3.0.jar!/:1.3.0]
        at rx.Completable$32.call(Completable.java:2253) ~[rxjava-1.3.0.jar!/:1.3.0]
        at rx.Completable$32.call(Completable.java:2250) ~[rxjava-1.3.0.jar!/:1.3.0]
        at rx.Observable.unsafeSubscribe(Observable.java:10256) [rxjava-1.3.0.jar!/:1.3.0]
        at rx.internal.operators.OperatorMerge$MergeSubscriber.onNext(OperatorMerge.java:248) [rxjava-1.3.0.jar!/:1.3.0]
        at rx.internal.operators.OperatorMerge$MergeSubscriber.onNext(OperatorMerge.java:148) [rxjava-1.3.0.jar!/:1.3.0]
        at rx.internal.operators.OnSubscribeMap$MapSubscriber.onNext(OnSubscribeMap.java:77) [rxjava-1.3.0.jar!/:1.3.0]
        at rx.internal.operators.OnSubscribeMap$MapSubscriber.onNext(OnSubscribeMap.java:77) [rxjava-1.3.0.jar!/:1.3.0]
        at rx.internal.util.ScalarSynchronousObservable$WeakSingleProducer.request(ScalarSynchronousObservable.java:276) [rxjava-1.3.0.jar!/:1.3.0]
        at rx.Subscriber.setProducer(Subscriber.java:211) [rxjava-1.3.0.jar!/:1.3.0]
        at rx.internal.operators.OnSubscribeMap$MapSubscriber.setProducer(OnSubscribeMap.java:102) [rxjava-1.3.0.jar!/:1.3.0]
        at rx.internal.operators.OnSubscribeMap$MapSubscriber.setProducer(OnSubscribeMap.java:102) [rxjava-1.3.0.jar!/:1.3.0]
        at rx.internal.util.ScalarSynchronousObservable$JustOnSubscribe.call(ScalarSynchronousObservable.java:138) [rxjava-1.3.0.jar!/:1.3.0]
        at rx.internal.util.ScalarSynchronousObservable$JustOnSubscribe.call(ScalarSynchronousObservable.java:129) [rxjava-1.3.0.jar!/:1.3.0]
        at rx.Observable.unsafeSubscribe(Observable.java:10256) [rxjava-1.3.0.jar!/:1.3.0]
        at rx.internal.operators.OnSubscribeMap.call(OnSubscribeMap.java:48) [rxjava-1.3.0.jar!/:1.3.0]
        at rx.internal.operators.OnSubscribeMap.call(OnSubscribeMap.java:33) [rxjava-1.3.0.jar!/:1.3.0]
        at rx.Observable.unsafeSubscribe(Observable.java:10256) [rxjava-1.3.0.jar!/:1.3.0]
        at rx.internal.operators.OnSubscribeMap.call(OnSubscribeMap.java:48) [rxjava-1.3.0.jar!/:1.3.0]
        at rx.internal.operators.OnSubscribeMap.call(OnSubscribeMap.java:33) [rxjava-1.3.0.jar!/:1.3.0]
        at rx.internal.operators.OnSubscribeLift.call(OnSubscribeLift.java:48) [rxjava-1.3.0.jar!/:1.3.0]
        at rx.internal.operators.OnSubscribeLift.call(OnSubscribeLift.java:30) [rxjava-1.3.0.jar!/:1.3.0]
        at rx.Observable.unsafeSubscribe(Observable.java:10256) [rxjava-1.3.0.jar!/:1.3.0]
        at rx.internal.operators.OnSubscribeRedo$2.call(OnSubscribeRedo.java:273) [rxjava-1.3.0.jar!/:1.3.0]
        at rx.internal.schedulers.TrampolineScheduler$InnerCurrentThreadScheduler.enqueue(TrampolineScheduler.java:73) [rxjava-1.3.0.jar!/:1.3.0]
        at rx.internal.schedulers.TrampolineScheduler$InnerCurrentThreadScheduler.schedule(TrampolineScheduler.java:52) [rxjava-1.3.0.jar!/:1.3.0]
        at rx.internal.operators.OnSubscribeRedo$5.request(OnSubscribeRedo.java:361) [rxjava-1.3.0.jar!/:1.3.0]
        at rx.Subscriber.setProducer(Subscriber.java:209) [rxjava-1.3.0.jar!/:1.3.0]
        at rx.internal.operators.OnSubscribeRedo.call(OnSubscribeRedo.java:353) [rxjava-1.3.0.jar!/:1.3.0]
        at rx.internal.operators.OnSubscribeRedo.call(OnSubscribeRedo.java:47) [rxjava-1.3.0.jar!/:1.3.0]
        at rx.Observable.unsafeSubscribe(Observable.java:10256) [rxjava-1.3.0.jar!/:1.3.0]
        at rx.Completable$10.call(Completable.java:588) [rxjava-1.3.0.jar!/:1.3.0]
        at rx.Completable$10.call(Completable.java:567) [rxjava-1.3.0.jar!/:1.3.0]
        at rx.Completable.unsafeSubscribe(Completable.java:2035) [rxjava-1.3.0.jar!/:1.3.0]
        at rx.Completable.unsafeSubscribe(Completable.java:2083) [rxjava-1.3.0.jar!/:1.3.0]
        at rx.Completable.unsafeSubscribe(Completable.java:2067) [rxjava-1.3.0.jar!/:1.3.0]
        at rx.Completable$32.call(Completable.java:2253) [rxjava-1.3.0.jar!/:1.3.0]
        at rx.Completable$32.call(Completable.java:2250) [rxjava-1.3.0.jar!/:1.3.0]
        at rx.Observable.unsafeSubscribe(Observable.java:10256) [rxjava-1.3.0.jar!/:1.3.0]
        at rx.internal.operators.OnSubscribeRedo$2.call(OnSubscribeRedo.java:273) [rxjava-1.3.0.jar!/:1.3.0]
        at rx.internal.schedulers.TrampolineScheduler$InnerCurrentThreadScheduler.enqueue(TrampolineScheduler.java:73) [rxjava-1.3.0.jar!/:1.3.0]
        at rx.internal.schedulers.TrampolineScheduler$InnerCurrentThreadScheduler.schedule(TrampolineScheduler.java:52) [rxjava-1.3.0.jar!/:1.3.0]
        at rx.internal.operators.OnSubscribeRedo$5.request(OnSubscribeRedo.java:361) [rxjava-1.3.0.jar!/:1.3.0]
        at rx.Subscriber.setProducer(Subscriber.java:209) [rxjava-1.3.0.jar!/:1.3.0]
        at rx.internal.operators.OnSubscribeRedo.call(OnSubscribeRedo.java:353) [rxjava-1.3.0.jar!/:1.3.0]
        at rx.internal.operators.OnSubscribeRedo.call(OnSubscribeRedo.java:47) [rxjava-1.3.0.jar!/:1.3.0]
        at rx.Observable.unsafeSubscribe(Observable.java:10256) [rxjava-1.3.0.jar!/:1.3.0]
        at rx.Completable$10.call(Completable.java:588) [rxjava-1.3.0.jar!/:1.3.0]
        at rx.Completable$10.call(Completable.java:567) [rxjava-1.3.0.jar!/:1.3.0]
        at rx.Completable.unsafeSubscribe(Completable.java:2035) [rxjava-1.3.0.jar!/:1.3.0]
        at rx.Completable.unsafeSubscribe(Completable.java:2083) [rxjava-1.3.0.jar!/:1.3.0]
        at rx.Completable.unsafeSubscribe(Completable.java:2067) [rxjava-1.3.0.jar!/:1.3.0]
        at rx.Completable$32.call(Completable.java:2253) [rxjava-1.3.0.jar!/:1.3.0]
        at rx.Completable$32.call(Completable.java:2250) [rxjava-1.3.0.jar!/:1.3.0]
        at rx.Observable.unsafeSubscribe(Observable.java:10256) [rxjava-1.3.0.jar!/:1.3.0]
        at rx.internal.operators.OperatorMerge$MergeSubscriber.onNext(OperatorMerge.java:248) [rxjava-1.3.0.jar!/:1.3.0]
        at rx.internal.operators.OperatorMerge$MergeSubscriber.onNext(OperatorMerge.java:148) [rxjava-1.3.0.jar!/:1.3.0]
        at rx.internal.operators.OnSubscribeMap$MapSubscriber.onNext(OnSubscribeMap.java:77) [rxjava-1.3.0.jar!/:1.3.0]
        at rx.internal.operators.OnSubscribeFilter$FilterSubscriber.onNext(OnSubscribeFilter.java:76) [rxjava-1.3.0.jar!/:1.3.0]
        at rx.internal.operators.OnSubscribeTimerOnce$1.call(OnSubscribeTimerOnce.java:49) [rxjava-1.3.0.jar!/:1.3.0]
        at rx.internal.schedulers.EventLoopsScheduler$EventLoopWorker$2.call(EventLoopsScheduler.java:189) [rxjava-1.3.0.jar!/:1.3.0]
        at rx.internal.schedulers.ScheduledAction.run(ScheduledAction.java:55) [rxjava-1.3.0.jar!/:1.3.0]
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) [?:1.8.0_121]
        at java.util.concurrent.FutureTask.run(FutureTask.java:266) [?:1.8.0_121]
        at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(ScheduledThreadPoolExecutor.java:180) [?:1.8.0_121]
        at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:293) [?:1.8.0_121]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142) [?:1.8.0_121]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617) [?:1.8.0_121]
        at java.lang.Thread.run(Thread.java:745) [?:1.8.0_121]
```

What does it mean?

**Comment by dnault** [comment]
The java-dcp-client project is being promoted from couchbaselabs to the primary couchbase org. As part of this change, issues reported via GitHub are being migrated to the Couchbase Jira.

To track the progress of this issue, please follow https://issues.couchbase.com/browse/JDCP-58
